default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: 'slackbot'
  host: 127.0.0.1
  username: root
  password:

test:
  <<: *default
  database: 'slackbot'
  host: 127.0.0.1
  username: root
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>
